name: application_amende
description: Application de gestion des amendes (MVP Flutter + Firebase)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase (FlutterFire)
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  firebase_storage: ^13.0.3

  # Notifications / media
  flutter_local_notifications: ^19.5.0
  image_picker: ^1.1.2
  # camera: ^0.11.0+2   # active si tu en as besoin maintenant

  # OCR (pour plus tard quand on attaquera le scan)
  google_mlkit_text_recognition: ^0.15.0

  # UI optionnel
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
